### ISSUE TITLE
Issue with non-existing path to BlazorStatic.csproj

### ISSUE THREAD

**Issue by patricktcoakley** [BlazorStatic/BlazorStaticMinimalBlog#11]
Hey, I've been playing around with this project and really enjoy it. I noticed that this template is referencing a relative path to the BlazorStatic.csproj which will won't let you run it out of the box. I assume this is a leftover from having this template in the main repo, so it should be an easy fix but perhaps it would make sense to remove the templates from the library repo and just keep them in separate repos.

Here is what I'm referring to:
```
    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <!-- for debugging when running from BlazorStaticWebsite.sln-->
        <ProjectReference Include="../../../../src/BlazorStatic.csproj"/>
    </ItemGroup>
```

Thanks!

**Comment by tesar-tech** [comment]
Hi, thank you for reporting the issue. You are right; it should not be there, but there is a catch.

The `.csproj` actually serves three purposes:

- It will be copied as a template when you click the green `Use template` button on GitHub. I suspect that's what you did (?). That's the case with the issue.
- It will be copied with the `dotnet new` command. In that case, thanks to `<!--#if (UseInTemplate)-->` and [this condition](https://github.com/tesar-tech/BlazorStatic/blob/226d98600f835a2abb64d0d36133e7489a30b183/BlazorStaticTemplates/templates/BlazorStaticMinimalBlogTemplate/.template-config/template.json#L34), most of the code is removed, and you end up with a clean `.csproj`.
- It is used in `BlazorStaticWebsite.sln`. This is the only case where referencing the project is necessary. The reason is to keep everything under one solution, thus speeding up development. I can run and check the minimal blog with the current WIP version of BlazorStatic. It was necessary back when the library was changing rapidly, but maybe now is the time to remove the reference and only update the minimal blog when a new BlazorStatic version is released.

It was actually not part of the main repo initially. I added it in the last version through a git submodule to make the `dotnet new` templates work (mainly the ci/cd process).

Does that make sense? Can you think of any other solution now?
The more I think about it the more I am inclining towards deleting the reference...

**Comment by patricktcoakley** [comment]
Sure, it makes sense to me. Personally I don't think it makes sense to keep any references to the templates or their code in the library repo and keep everything separately since they shouldn't have any relationship, but that's just how I might approach it.

**Comment by tesar-tech** [comment]
I have removed the reference and cleaned up the related issues. It looks better now—thanks for pointing it out.

However, it's not entirely accurate to say that it doesn't have any relationship, at least from the `dotnet pack` standpoint. Now, we have a build action that creates the BlazorStatic nuget package and also packs and creates the nuget package for templates. I suspect that there will be more templates in the future, and we will need some sort of "roofing" to manage all the templates, allowing them to be packed together from different repositories. I think it would be better to have a `BlazorStatic.Templates` repository, which would handle the packaging and pushing of the NuGet packages. But for now, the main repository serves as the roofing project, primarily for "dev comfort." It doesn't share any code; it's just part of the same gh repo.

There's a much-needed discussion on how to approach the templating properly. It’s still in the early stages, but I want to do it right. I'll continue the discussion in the second issue you created in the main repository, as it's closely related.

Once again, thank you for your suggestions. I really appreciate these reviews—they help make BlazorStatic better.

**Comment by patricktcoakley** [comment]
No problem, I hope I can get more involved with the project once I use it more and offer some code changes. I agree having a templates repo that handles everything would be better in the future, but I've not really worked with dotnet templates to have a strong opinion outside of using them as a user.  Feel free to mark it as close if this resolves this specific discussion.
