### ISSUE TITLE
Suggestion: Move off of Tailwind

### ISSUE THREAD

**Issue by patricktcoakley** [BlazorStatic/BlazorStaticMinimalBlog#12]
Tailwind is great but it feels out of place here, and I think it would make more sense to focus on using Blazor component libraries, such as MudBlazor or FluentUI, instead of Tailwind for the purposes of BlazorStatic being a Blazor-centric library.

**Comment by tesar-tech** [comment]
Tailwind is here because of my personal preference, yes. From the start of the BlazorStatic journey, I’ve made an effort to keep it style- and component-library agnostic. I would say this is reflected in the templates. The current state of one template simply reflects my limited resources to create more. As you can tell by looking at the page, I’m not the ideal person to bring a template to its full visual potential. Maintaining the template also requires a certain amount of ongoing effort to keep it updated.

In the future, I envision multiple templates with a variety of styles and component libraries, so no single one will be the default. However, I would like to keep the Tailwind template available.

I don't want to re-create this template using something else, but if you feel up to the task, I’d really welcome another template. Just wait a few days, as I'm currently in the process of rebuilding the project structure. Soon, this will simply be the output of `dotnet new BlazorStaticMinimalBlog`, as you can already see in the by-build branch: [GitHub link](https://github.com/BlazorStatic/BlazorStaticMinimalBlog/tree/by-build) the real template will be either in the main repo or later in `BlazorStatic/Templates`

**Comment by patricktcoakley** [comment]
I think it will make more sense to stuff all of the templates inside of a Templates repo because it would also make it easier to accept user-submitted ones without having it be tied to the main project.  Ideally the UX for a new one would be `dotnet net BlazorStatic.TemplateName`. You'd also wanna make sure any of the submissions contain libraries etc that are safe for use under MIT etc, including your current one, so I'd probably include a license in the Templates repo when it gets created. I really like how [Avalonia](https://github.com/AvaloniaUI/avalonia-dotnet-templates) handles its templates so it's worth studying.

I have been experimenting with a few Blazor component libraries and haven't landed on what I want to use myself, but if I can make something similar to the MinimalBlog template I can try to submit it.
